---
abstract: 'Simple command-line search of CPAN using the metacpan API'
author:
  - 'Brock Wilcox <awwaiid@thelackthereof.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-metacpansearch
requires:
  Getopt::Std: 0
  JSON: 0
  LWP::Simple: 0
  URL::Encode: 0
  strict: 0
version: 0.01
